# Generated by Django 6.1 on 2026-08-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_invite_token_user_invite_token_expires_at'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Required for COMPANY_USER role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company'),
        ),
    ]
